# Generated by gallery/generate.py; do not hand-edit.
forceload add 204 212 236 228
fill 204 100 212 236 104 228 minecraft:air replace
fill 204 99 212 236 99 228 minecraft:smooth_stone replace
# 01 joltik-half-walking-stone-r0
setblock 208 100 216 cobblemonstonestatues:pokemon_statue replace
data merge block 208 100 216 {SpeciesId:"cobblemon:joltik",FormId:"Normal",AspectsCsv:"",AnimationName:"walking",Scale:"HALF",Material:"STONE",Rotation45:0,StoneSeed:0L}
# 02 bulbasaur-normal-sleep-stone-r1
setblock 216 100 216 cobblemonstonestatues:pokemon_statue replace
data merge block 216 100 216 {SpeciesId:"cobblemon:bulbasaur",FormId:"Normal",AspectsCsv:"",AnimationName:"sleep",Scale:"NORMAL",Material:"STONE",Rotation45:1,StoneSeed:0L}
# 03 pikachu-double-shoulder-left-gold-r3
setblock 224 100 216 cobblemonstonestatues:pokemon_statue replace
data merge block 224 100 216 {SpeciesId:"cobblemon:pikachu",FormId:"Normal",AspectsCsv:"",AnimationName:"shoulder_left",Scale:"DOUBLE",Material:"GOLD_BLOCK",Rotation45:3,StoneSeed:0L}
# 04 hisuian-decidueye-triple-fly-stone-r5
setblock 232 100 216 cobblemonstonestatues:pokemon_statue replace
data merge block 232 100 216 {SpeciesId:"cobblemon:decidueye",FormId:"Hisui",AspectsCsv:"hisuian",AnimationName:"fly",Scale:"TRIPLE",Material:"STONE",Rotation45:5,StoneSeed:0L}
# 05 stone-control
setblock 208 100 224 minecraft:stone replace
# 06 gold-control
setblock 216 100 224 minecraft:gold_block replace
# 07 orphan-statue-proxy
setblock 224 100 224 cobblemonstonestatues:statue_proxy replace
# 08 unknown-species-master
setblock 232 100 224 cobblemonstonestatues:pokemon_statue replace
data merge block 232 100 224 {SpeciesId:"cobblemon:atmons_unknown_species",FormId:"Normal",AspectsCsv:"",AnimationName:"portrait",Scale:"NORMAL",Material:"STONE",Rotation45:0,StoneSeed:0L}
tellraw @a [{"text":"Built the bounded eight-cell Stone Statues gallery.","color":"green"}]
