# Generated by gallery/generate.py; do not hand-edit.
scoreboard objectives add stone_statues_gallery dummy
scoreboard players set #checked stone_statues_gallery 0
scoreboard players set #failures stone_statues_gallery 0
execute unless block 208 100 216 cobblemonstonestatues:pokemon_statue run scoreboard players add #failures stone_statues_gallery 1
execute unless data block 208 100 216 {SpeciesId:"cobblemon:joltik",FormId:"Normal",AspectsCsv:"",AnimationName:"walking",Scale:"HALF",Material:"STONE",Rotation45:0,StoneSeed:0L} run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 216 100 216 cobblemonstonestatues:pokemon_statue run scoreboard players add #failures stone_statues_gallery 1
execute unless data block 216 100 216 {SpeciesId:"cobblemon:bulbasaur",FormId:"Normal",AspectsCsv:"",AnimationName:"sleep",Scale:"NORMAL",Material:"STONE",Rotation45:1,StoneSeed:0L} run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 224 100 216 cobblemonstonestatues:pokemon_statue run scoreboard players add #failures stone_statues_gallery 1
execute unless data block 224 100 216 {SpeciesId:"cobblemon:pikachu",FormId:"Normal",AspectsCsv:"",AnimationName:"shoulder_left",Scale:"DOUBLE",Material:"GOLD_BLOCK",Rotation45:3,StoneSeed:0L} run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 232 100 216 cobblemonstonestatues:pokemon_statue run scoreboard players add #failures stone_statues_gallery 1
execute unless data block 232 100 216 {SpeciesId:"cobblemon:decidueye",FormId:"Hisui",AspectsCsv:"hisuian",AnimationName:"fly",Scale:"TRIPLE",Material:"STONE",Rotation45:5,StoneSeed:0L} run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 208 100 224 minecraft:stone run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 216 100 224 minecraft:gold_block run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 224 100 224 cobblemonstonestatues:statue_proxy run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless block 232 100 224 cobblemonstonestatues:pokemon_statue run scoreboard players add #failures stone_statues_gallery 1
execute unless data block 232 100 224 {SpeciesId:"cobblemon:atmons_unknown_species",FormId:"Normal",AspectsCsv:"",AnimationName:"portrait",Scale:"NORMAL",Material:"STONE",Rotation45:0,StoneSeed:0L} run scoreboard players add #failures stone_statues_gallery 1
scoreboard players add #checked stone_statues_gallery 1
execute unless score #checked stone_statues_gallery matches 8 run scoreboard players add #failures stone_statues_gallery 1
execute if score #failures stone_statues_gallery matches 0 run tellraw @a [{"text":"Stone Statues gallery verification passed: 8 cells.","color":"green"}]
execute unless score #failures stone_statues_gallery matches 0 run tellraw @a [{"text":"Stone Statues gallery verification failed.","color":"red"}]
